Add readme
husarion/ur-docker pull request #5
Opened 2023-02-15 10:56 UTC by pkowalsk1

2023-02-15 14:17 UTC, KmakD requested changes

2023-02-15 14:17 UTC, KmakD commented on README.md
> +## [UR5e-custom](./demo/ur5e-custom/)
```suggestion

## [UR5e-custom](./demo/ur5e-custom/)
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +## [UR5e-onrobot-rg2](./demo/ur5e-onrobot-rg2/)
```suggestion

## [UR5e-onrobot-rg2](./demo/ur5e-onrobot-rg2/)
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +Run or simulate the Panther robot equipped with a UR5e manipulator, Velodyne Puck LiDAR, Zed2i camera, and Onrobot RG2 gripper. Moveit Wizard Manager can be used to create a [custom package](#customi
```suggestion
Run or simulate the Panther robot equipped with a UR5e manipulator, Velodyne Puck LiDAR, Zed2i camera, and OnRobot RG2 gripper. Moveit Wizard Manager can be used to create a [custom package](#customize-your-moveit_config-package-optional) based on [ur5e_onrobot_rg2_moveit_config](https://github.com/husarion/ur_ros/tree/main/ur5e_onrobot_rg2_moveit_config), making it possible to personalize robot setup.
```
`#customize-your-moveit_config-package` reference does not exists, I guess it is missing `optional` part

2023-02-15 14:17 UTC, KmakD commented on README.md
> +Run or simulate the Panther robot equipped with a UR5e manipulator, Velodyne Puck LiDAR, and Realsense d435i camera. Moveit Wizard Manager can be used to create a [custom package](#customize-your-mov
```suggestion
Run or simulate the Panther robot equipped with a UR5e manipulator, Velodyne Puck LiDAR, and Realsense d435i camera. Moveit Wizard Manager can be used to create a [custom package](#customize-your-moveit_config-package-optional) based on [ur5e_moveit_config](https://github.com/husarion/ur_ros/tree/main/ur5e_moveit_config), making it possible to personalize robot setup.
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +Docker image is utilized to run or simulate the Panther robot equipped with a UR3 manipulator. Moveit Wizard Manager can be used to create a [custom package](#customize-your-moveit_config-package) ba
```suggestion
Docker image is utilized to run or simulate the Panther robot equipped with a UR3 manipulator. Moveit Wizard Manager can be used to create a [custom package](#customize-your-moveit_config-package-optional) based on [ur3_moveit_config](https://github.com/husarion/ur_ros/tree/main/ur3_moveit_config), making it possible to personalize robot setup.
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +The docker configurations shown here are example use cases where the URxx manipulator is controlled using the Moveit package. You can customize them as follows:
```suggestion

The docker configurations shown here are example use cases where the URxx manipulator is controlled using the Moveit package. You can customize them as follows:
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +1. Connect to the robot's WiFi network and connect via `ssh` to the internal computer. On the internal computer of the Panther robot (HP Z2 or Intel NUC) run `demo/power_on_ur_controller.sh`:
```suggestion

1. Connect to the robot's WiFi network and connect via `ssh` to the internal computer. On the internal computer of the Panther robot (HP Z2 or Intel NUC) run `demo/power_on_ur_controller.sh`:
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +URxx robot driver needs a calibration file. You can get this using `demo/compose.calibration.yaml` file:
```suggestion

URxx robot driver needs a calibration file. You can get this using `demo/compose.calibration.yaml` file:
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +In your browser, go to this [link](http://10.15.20.3:8080/vnc.html) and use Rviz to manipulate UR5e.
```suggestion
In your browser, go to [10.15.20.3:8080/vnc.html](http://10.15.20.3:8080/vnc.html) and use Rviz to manipulate UR5e.
```

2023-02-15 14:17 UTC, KmakD commented on README.md
> +5. Go to `program` and run `external_control` URcap. If you use Onrobot RG2 gripper you shoud run `husarion_ext_control.urp` program. If it did not come with the robot then you can find it [here](htt
https://github.com/husarion/ur-onrobot-rg2-docker/tree/main/ur-programs does not exists

2023-02-15 14:17 UTC, KmakD commented on README.md
> +1. If there is a need then modify the sample package ([link](#customize-your-moveit_config-package)).
```suggestion

1. If there is a need then modify the sample package ([link](#customize-your-moveit_config-package-optional)).
```

2023-02-15 14:34 UTC, KmakD reviewed
You may also add some reference to ur-onrobot-rg2-docker repo on how to use gripper

2023-02-16 10:39 UTC, pkowalsk1 commented on README.md
> +5. Go to `program` and run `external_control` URcap. If you use Onrobot RG2 gripper you shoud run `husarion_ext_control.urp` program. If it did not come with the robot then you can find it [here](htt
See https://github.com/husarion/ur-onrobot-rg2-docker/pull/3. It moves `demo/ur-programs` to `ur-programs`. It should work.

2023-02-16 10:47 UTC, pkowalsk1 commented
> You may also add some reference to ur-onrobot-rg2-docker repo on how to use gripper

A small reference on the subject is [here](https://github.com/husarion/ur-docker/pull/5/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R24). Add something else?

2023-02-16 11:52 UTC, KmakD approved these changes

2023-02-16 11:52 UTC, merged